### ISSUE TITLE
[Suggesiton] Noise reduction code

### ISSUE THREAD

**Issue by thetobby** [charlie-foxtrot/RTLSDR-Airband#3]
Perhaps this codebase can be useful?
http://habrahabr.ru/post/243977/

Sourcecode:
http://cgit.freedesktop.org/pulseaudio/webrtc-audio-processing/

**Comment by thetobby** [comment]
An easier implementation may be to just route the audio through a loopback audio interface with pulseaudio since the audio is not time sensitive instead of adding the code into the program itself.

**Comment by bovine** [comment]
@thetobby are you saying that you've tested the effect of the "echo-cancellation" filter and found that to be the most effective one? It looks like there is also "noise-supression" filter in that codebase which sounds like it might be the better option:

https://cgit.freedesktop.org/pulseaudio/webrtc-audio-processing/tree/webrtc/modules/audio_processing

**Comment by barjac** [comment]
I find that most 'noise' that impairs legibility of air-band reception is above the required bandwidth for speech and can be removed by using the graphic equalizer and low pass filter in PulseEffects, set to cut around 2.7kHz.
https://github.com/wwmm/pulseeffects

**Comment by cblknittights** [comment]
>can be removed by using the graphic equalizer and low pass filter in PulseEffects

Not everyone uses pulse* . I am strictly ALSA, and pulse* is one of the first things I apt-get purge on any setup.

**Comment by Strykar** [comment]
Any noise reduction code would be useful, even using Sox.
I'm not a fan of Pulse tho I do use it on some desktops.

**Comment by danmilon** [comment]
https://github.com/szpajder/RTLSDR-Airband/pull/112 is related.

**Comment by charlie-foxtrot** [comment]
no additional plans to add noise reduction code, closing
