### ISSUE TITLE
[FEATURE] Allow different ampfactors for each frequency in scan mode

### ISSUE THREAD

**Issue by steve1515** [charlie-foxtrot/RTLSDR-Airband#305]
Is it possible to have different ampfactor's for each frequency in the channel section in scan mode? If not, I'd like to request this feature if it's possible.

**Comment by charlie-foxtrot** [comment]
is `ampfacto`r for the output volume?  if so thats in #369

**Comment by steve1515** [comment]
Yes. It was used something like <1.0 lowers volume and >1.0 amplifies volume in mixers, but was never a feature per channel in scan mode.
