### ISSUE TITLE
[BUG] notch filter is being ignored?

### ISSUE THREAD

**Issue by israelgoldstein** [charlie-foxtrot/RTLSDR-Airband#390]
**Describe your environment**

  - RTLSDR-Airband version you are using (stable release number or branch/commit): RTLSDR-Airband version 4.1.1
  - `make` options used to build the program:
  - Hardware platform (eg. x86_64, Raspberry Pi v4):
  - Operating system name and version: 

**What happened?**
I have a notch set with a PL (CTCSS) 107.2 - but it seems that the rtl_airband is ignoring that value? it is decoding all other PL's too

**What you expected to happen?**
i expect only the PL/CTCSS i have set to be decoded
**Steps to Reproduce**

**Additional context**
Add any other relevant information about the problem here.

**Your rtl_airband.conf file**
{
        #disable = true;
        freq = 155.2650;
        lowpass = 3200;
        highpass = 200;
        bandwidth = 5000;
        modulation = "nfm";
        notch = 107.2;
        outputs: (
          {
            #disable = true;
            type = "file";
            directory = "/home/pi/scripts/rtlairband_recordings/Conv_01/2001/2001093";
            filename_template = "Washington Twp - EMS Ops";
            split_on_transmission = true;
            include_freq = true;
          }
        );
      },
      {
        #disable = true;
        freq = 155.2500;
        lowpass = 3200;
        highpass = 200;
        bandwidth = 5000;
        modulation = "nfm";
        notch = 110.9;
        outputs: (
          {
            #disable = true;
            type = "file";
            directory = "/home/pi/scripts/rtlairband_recordings/Conv_01/2001/2001094";
            filename_template = "North Arlington - PD-MS Dispatch";
            split_on_transmission = true;
            include_freq = true;
          }
        );
      }

**Comment by charlie-foxtrot** [comment]
Setting `notch` will suppress audio but will not perform any squelch.  Setting `ctcss` will do squelch but allow the tone to pass through to the audio.  See https://github.com/charlie-foxtrot/RTLSDR-Airband/wiki/CTCSS for more.

It sounds like you may want to be setting both, ie:

```
notch = 107.2;
ctcss = 107.2;
```




is used to suppress a frequency, `ctcss` is used to
