### ISSUE TITLE
CTCSS filter request

### ISSUE THREAD

**Issue by itnavigate** [charlie-foxtrot/RTLSDR-Airband#82]
I find myself needing to remove CTCSS  tone from a series of NFM feeds to broadcastify.

Is this something that cane be (easily?) implemented with rtl_airband?

**Comment by szpajder** [comment]
Yep, I have a couple of ideas related to audio filtering on my TODO list, including this one.

**Comment by rec9140** [comment]
Any chance that this will also allow the code to select only a given PL on channels which have multiple users ie: one channel in my area is shared by a local aeromedevac and due to location and signal another user I don't care about, only difference is PL.  In the setup you would specify the pl=127.3 or something.

**Comment by szpajder** [comment]
I might try it, but you'll be testing it :) I don't have a lot of CTCSS signals here around.

**Comment by itnavigate** [comment]
I'm happy to test. I have sufficient ctcss

**Comment by szpajder** [comment]
Nope. When it is, I'll post info here.

**Comment by redrob** [comment]
+1 for CTCSS Support. :)

**Comment by dh47** [comment]
Just checking in to see if any progress has been made?

**Comment by szpajder** [comment]
Not a whole lot, but there is support for bandpass filtering in outputs which use MP3 compression, so it can be used to filter out CTCSS tones as well. See https://github.com/szpajder/RTLSDR-Airband/pull/112 .

**Comment by b4sh** [comment]
My method to filter CTCSS (on client side).

play -t mp3 http://192.168.0.80:8000/radioscanner highpass 300 lowpass 3000

#112 not fork for me.

**Comment by charlie-foxtrot** [comment]
Doesn't select only a given PL, but #159 adds a notch filter that can be used to remove a CTCSS tone

**Comment by charlie-foxtrot** [comment]
CTCSS support in #368
